apiVersion: v1
kind: Service
metadata:
  name: {{ include "sit727-2.3d.fullname" . }}
  labels:
    {{- include "sit727-2.3d.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/servicetag: server
