apiVersion: v1
kind: Service
metadata:
  name: {{ include "sit727-2.3d.fullname" . }}-database
  labels:
    {{- include "sit727-2.3d.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/servicetag: database